[package]
name = "esc_server"
version = "0.1.0"
edition = "2021"

[dependencies]
bson = "2.4.0"
esc_common = { path = "../esc_common" }
tokio = { version = "1.21.2", features = [
    "macros",
    "rt-multi-thread",
    "net",
    "io-util",
    "process",
] }
